<?php
/* 
 * Generated by CRUDigniter v3.0 Beta 
 * www.crudigniter.com
 */
 
class Book extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Test_product_model');
        
    } 

    /*
     * Listing of orders
     */
    function index() {
        
        $data['test_product'] = $this->Test_product_model->get_all_test_product();
        $data['title']="จองแพ๊คเกจ";
        $this->load->view('Book/index',$data);
    }

    function Reserved()
    {
        
        $ar=array(

            "sesion_total_ticket"       =>$this->input->post('total_ticket'),
            "sesion_date"               => $this->input->post('date'),
            "sesion_total_price"        =>$this->input->post('total_price')

        );
        $this->session->set_userdata($ar);
        
        //$this->load->view('Book/Reserved');

        $data['_view'] = 'Book/Reserved';
        $this->load->view('layouts/main',$data);
    }

    
    
}
