<?php
/* 
 * Generated by CRUDigniter v3.0 Beta 
 * www.crudigniter.com
 */
 
class Book extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Test_product_model');
        
    } 

    /*
     * Listing of orders
     */
    function index() {
        
        $data['test_product'] = $this->Test_product_model->get_all_test_product();
        $data['title']="จองแพ๊คเกจ";
        $this->load->view('Book/index',$data);
    }

    
    
}
