<?php
/* 
 * Generated by CRUDigniter v3.0 Beta 
 * www.crudigniter.com
 */
 
class Order extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Order_model');
    } 

    /*
     * Listing of orders
     */
    function index()
    {
        $data['orders'] = $this->Order_model->get_all_orders();

        $data['_view'] = 'order/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new order
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'is_incentive' => $this->input->post('is_incentive'),
				'is_window_seat' => $this->input->post('is_window_seat'),
				'is_pathway_seat' => $this->input->post('is_pathway_seat'),
				'in_process' => $this->input->post('in_process'),
				'is_pending' => $this->input->post('is_pending'),
				'is_read' => $this->input->post('is_read'),
				'product_id' => $this->input->post('product_id'),
				'stock_id' => $this->input->post('stock_id'),
				'number_of_adults' => $this->input->post('number_of_adults'),
				'number_of_children' => $this->input->post('number_of_children'),
				'number_of_singleroom' => $this->input->post('number_of_singleroom'),
				'number_of_doubleroom' => $this->input->post('number_of_doubleroom'),
				'number_of_tripleroom' => $this->input->post('number_of_tripleroom'),
				'is_seafood_allergy' => $this->input->post('is_seafood_allergy'),
				'is_vegetarian' => $this->input->post('is_vegetarian'),
				'is_islam' => $this->input->post('is_islam'),
				'order_price' => $this->input->post('order_price'),
				'insurance_type' => $this->input->post('insurance_type'),
				'insurance_amount' => $this->input->post('insurance_amount'),
				'insurance_start' => $this->input->post('insurance_start'),
				'insurance_stop' => $this->input->post('insurance_stop'),
				'insurance_country' => $this->input->post('insurance_country'),
				'addon_price' => $this->input->post('addon_price'),
				'discount' => $this->input->post('discount'),
				'surcharge' => $this->input->post('surcharge'),
				'grand_total' => $this->input->post('grand_total'),
				'paid_amount' => $this->input->post('paid_amount'),
				'member_id' => $this->input->post('member_id'),
				'created_at' => $this->input->post('created_at'),
				'order_status' => $this->input->post('order_status'),
				'modified_at' => $this->input->post('modified_at'),
				'handled_by' => $this->input->post('handled_by'),
				'aff_id' => $this->input->post('aff_id'),
				'order_add_on' => $this->input->post('order_add_on'),
				'other_detail' => $this->input->post('other_detail'),
				'order_memo' => $this->input->post('order_memo'),
            );
            
            $order_id = $this->Order_model->add_order($params);
            redirect('order/index');
        }
        else
        {            
            $data['_view'] = 'order/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a order
     */
    function edit($order_id)
    {   
        // check if the order exists before trying to edit it
        $data['order'] = $this->Order_model->get_order($order_id);
        
        if(isset($data['order']['order_id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'is_incentive' => $this->input->post('is_incentive'),
					'is_window_seat' => $this->input->post('is_window_seat'),
					'is_pathway_seat' => $this->input->post('is_pathway_seat'),
					'in_process' => $this->input->post('in_process'),
					'is_pending' => $this->input->post('is_pending'),
					'is_read' => $this->input->post('is_read'),
					'product_id' => $this->input->post('product_id'),
					'stock_id' => $this->input->post('stock_id'),
					'number_of_adults' => $this->input->post('number_of_adults'),
					'number_of_children' => $this->input->post('number_of_children'),
					'number_of_singleroom' => $this->input->post('number_of_singleroom'),
					'number_of_doubleroom' => $this->input->post('number_of_doubleroom'),
					'number_of_tripleroom' => $this->input->post('number_of_tripleroom'),
					'is_seafood_allergy' => $this->input->post('is_seafood_allergy'),
					'is_vegetarian' => $this->input->post('is_vegetarian'),
					'is_islam' => $this->input->post('is_islam'),
					'order_price' => $this->input->post('order_price'),
					'insurance_type' => $this->input->post('insurance_type'),
					'insurance_amount' => $this->input->post('insurance_amount'),
					'insurance_start' => $this->input->post('insurance_start'),
					'insurance_stop' => $this->input->post('insurance_stop'),
					'insurance_country' => $this->input->post('insurance_country'),
					'addon_price' => $this->input->post('addon_price'),
					'discount' => $this->input->post('discount'),
					'surcharge' => $this->input->post('surcharge'),
					'grand_total' => $this->input->post('grand_total'),
					'paid_amount' => $this->input->post('paid_amount'),
					'member_id' => $this->input->post('member_id'),
					'created_at' => $this->input->post('created_at'),
					'order_status' => $this->input->post('order_status'),
					'modified_at' => $this->input->post('modified_at'),
					'handled_by' => $this->input->post('handled_by'),
					'aff_id' => $this->input->post('aff_id'),
					'order_add_on' => $this->input->post('order_add_on'),
					'other_detail' => $this->input->post('other_detail'),
					'order_memo' => $this->input->post('order_memo'),
                );

                $this->Order_model->update_order($order_id,$params);            
                redirect('order/index');
            }
            else
            {
                $data['_view'] = 'order/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The order you are trying to edit does not exist.');
    } 

    /*
     * Deleting order
     */
    function remove($order_id)
    {
        $order = $this->Order_model->get_order($order_id);

        // check if the order exists before trying to delete it
        if(isset($order['order_id']))
        {
            $this->Order_model->delete_order($order_id);
            redirect('order/index');
        }
        else
            show_error('The order you are trying to delete does not exist.');
    }
    
}
