<?php
/* 
 * Generated by CRUDigniter v3.0 Beta 
 * www.crudigniter.com
 */
 
class Order_passenger extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Order_passenger_model');
    } 

    /*
     * Listing of order_passenger
     */
    function index()
    {
        $data['order_passenger'] = $this->Order_passenger_model->get_all_order_passenger();

        $data['_view'] = 'order_passenger/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new order_passenger
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'passenger_title' => $this->input->post('passenger_title'),
				'passenger_firstname' => $this->input->post('passenger_firstname'),
				'passenger_lastname' => $this->input->post('passenger_lastname'),
				'passenger_firstname_th' => $this->input->post('passenger_firstname_th'),
				'passenger_lastname_th' => $this->input->post('passenger_lastname_th'),
				'passenger_telephone' => $this->input->post('passenger_telephone'),
				'passenger_mobile' => $this->input->post('passenger_mobile'),
				'passenger_email' => $this->input->post('passenger_email'),
				'passenger_gender' => $this->input->post('passenger_gender'),
				'passenger_birthdate' => $this->input->post('passenger_birthdate'),
				'passenger_nationality' => $this->input->post('passenger_nationality'),
				'passenger_citizen_id' => $this->input->post('passenger_citizen_id'),
				'passenger_passport_id' => $this->input->post('passenger_passport_id'),
				'passenger_passport_issue' => $this->input->post('passenger_passport_issue'),
				'passenger_passport_expiry' => $this->input->post('passenger_passport_expiry'),
				'passenger_passport_authority' => $this->input->post('passenger_passport_authority'),
				'passenger_visa' => $this->input->post('passenger_visa'),
				'passenger_visa_expiry' => $this->input->post('passenger_visa_expiry'),
            );
            
            $order_passenger_id = $this->Order_passenger_model->add_order_passenger($params);
            redirect('order_passenger/index');
        }
        else
        {            
            $data['_view'] = 'order_passenger/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a order_passenger
     */
    function edit($order_id)
    {   
        // check if the order_passenger exists before trying to edit it
        $data['order_passenger'] = $this->Order_passenger_model->get_order_passenger($order_id);
        
        if(isset($data['order_passenger']['order_id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'passenger_title' => $this->input->post('passenger_title'),
					'passenger_firstname' => $this->input->post('passenger_firstname'),
					'passenger_lastname' => $this->input->post('passenger_lastname'),
					'passenger_firstname_th' => $this->input->post('passenger_firstname_th'),
					'passenger_lastname_th' => $this->input->post('passenger_lastname_th'),
					'passenger_telephone' => $this->input->post('passenger_telephone'),
					'passenger_mobile' => $this->input->post('passenger_mobile'),
					'passenger_email' => $this->input->post('passenger_email'),
					'passenger_gender' => $this->input->post('passenger_gender'),
					'passenger_birthdate' => $this->input->post('passenger_birthdate'),
					'passenger_nationality' => $this->input->post('passenger_nationality'),
					'passenger_citizen_id' => $this->input->post('passenger_citizen_id'),
					'passenger_passport_id' => $this->input->post('passenger_passport_id'),
					'passenger_passport_issue' => $this->input->post('passenger_passport_issue'),
					'passenger_passport_expiry' => $this->input->post('passenger_passport_expiry'),
					'passenger_passport_authority' => $this->input->post('passenger_passport_authority'),
					'passenger_visa' => $this->input->post('passenger_visa'),
					'passenger_visa_expiry' => $this->input->post('passenger_visa_expiry'),
                );

                $this->Order_passenger_model->update_order_passenger($order_id,$params);            
                redirect('order_passenger/index');
            }
            else
            {
                $data['_view'] = 'order_passenger/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The order_passenger you are trying to edit does not exist.');
    } 

    /*
     * Deleting order_passenger
     */
    function remove($order_id)
    {
        $order_passenger = $this->Order_passenger_model->get_order_passenger($order_id);

        // check if the order_passenger exists before trying to delete it
        if(isset($order_passenger['order_id']))
        {
            $this->Order_passenger_model->delete_order_passenger($order_id);
            redirect('order_passenger/index');
        }
        else
            show_error('The order_passenger you are trying to delete does not exist.');
    }
    
}
