<?php
/* 
 * Generated by CRUDigniter v3.0 Beta 
 * www.crudigniter.com
 */
 
class Order_passenger_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get order_passenger by order_id
     */
    function get_order_passenger($order_id)
    {
        return $this->db->get_where('order_passenger',array('order_id'=>$order_id))->row_array();
    }
    
    /*
     * Get all order_passenger
     */
    function get_all_order_passenger()
    {
        return $this->db->get('order_passenger')->result_array();
    }
    
    /*
     * function to add new order_passenger
     */
    function add_order_passenger($params)
    {
        $this->db->insert('order_passenger',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update order_passenger
     */
    function update_order_passenger($order_id,$params)
    {
        $this->db->where('order_id',$order_id);
        $response = $this->db->update('order_passenger',$params);
        if($response)
        {
            return "order_passenger updated successfully";
        }
        else
        {
            return "Error occuring while updating order_passenger";
        }
    }
    
    /*
     * function to delete order_passenger
     */
    function delete_order_passenger($order_id)
    {
        $response = $this->db->delete('order_passenger',array('order_id'=>$order_id));
        if($response)
        {
            return "order_passenger deleted successfully";
        }
        else
        {
            return "Error occuring while deleting order_passenger";
        }
    }
}
