<?php
/* 
 * Generated by CRUDigniter v3.0 Beta 
 * www.crudigniter.com
 */
 
class Order_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get order by order_id
     */
    function get_order($order_id)
    {
        return $this->db->get_where('orders',array('order_id'=>$order_id))->row_array();
    }
    
    /*
     * Get all orders
     */
    function get_all_orders()
    {
        return $this->db->get('orders')->result_array();
    }
    
    /*
     * function to add new order
     */
    function add_order($params)
    {
        $this->db->insert('orders',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update order
     */
    function update_order($order_id,$params)
    {
        $this->db->where('order_id',$order_id);
        $response = $this->db->update('orders',$params);
        if($response)
        {
            return "order updated successfully";
        }
        else
        {
            return "Error occuring while updating order";
        }
    }
    
    /*
     * function to delete order
     */
    function delete_order($order_id)
    {
        $response = $this->db->delete('orders',array('order_id'=>$order_id));
        if($response)
        {
            return "order deleted successfully";
        }
        else
        {
            return "Error occuring while deleting order";
        }
    }
}
