<?php
/* 
 * Generated by CRUDigniter v3.0 Beta 
 * www.crudigniter.com
 */
 
class Product_stock_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get product_stock by product_stock_id
     */
    function get_product_stock($product_stock_id)
    {
        return $this->db->get_where('product_stock',array('product_stock_id'=>$product_stock_id))->row_array();
    }
    
    /*
     * Get all product_stock
     */
    function get_all_product_stock()
    {
        return $this->db->get('product_stock')->result_array();
    }
    
    /*
     * function to add new product_stock
     */
    function add_product_stock($params)
    {
        $this->db->insert('product_stock',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update product_stock
     */
    function update_product_stock($product_stock_id,$params)
    {
        $this->db->where('product_stock_id',$product_stock_id);
        $response = $this->db->update('product_stock',$params);
        if($response)
        {
            return "product_stock updated successfully";
        }
        else
        {
            return "Error occuring while updating product_stock";
        }
    }
    
    /*
     * function to delete product_stock
     */
    function delete_product_stock($product_stock_id)
    {
        $response = $this->db->delete('product_stock',array('product_stock_id'=>$product_stock_id));
        if($response)
        {
            return "product_stock deleted successfully";
        }
        else
        {
            return "Error occuring while deleting product_stock";
        }
    }
}
